version: '3.8'

services:
  backend:
    build: ./backend
    container_name: music-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: music-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: music-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
